#!/bin/bash
#deletes all test cases-- fastpc, glpk, v2007
#deletes everything from output folder

prefixes=( May1_2009 apr17_2009 apr20_2009 jun18_2009 jun16_sparse TOMOG DIMACS 2011_Nov25 2011_sep20 )
suffix=_run_stats.csv
length=${#prefixes[*]}

#create all_run_stats.tmp
echo "" > all_run_stats.tmp

#append contents of run_stat files to all_run_stats
for prefix in ${prefixes[*]}
do
    file=$prefix$suffix
    echo $file
    cat $file >> all_run_stats.tmp
done

awk '{gsub(",", "\t"); print }' all_run_stats.tmp > all_run_stats

#delete temp file
rm -rf all_run_stats.tmp

#split data by algorithms
cat all_run_stats | grep Primal | grep -v 'NOT FOUND' > primal
cat all_run_stats | grep Dual | grep -v 'NOT FOUND' > dual
cat all_run_stats | grep Barrier | grep -v 'NOT FOUND' > barrier
cat all_run_stats | grep neal | grep -v 'NOT FOUND' > neal
cat all_run_stats | grep fastpc | grep -v 'NOT FOUND' > fastpc
cat fastpc > fandn
cat neal >> fandn

exit 0
