# -DNDEBUG turns off assert() statements
#CXXFLAGS = -O3

# for debugging
#CXXFLAGS = -g

# for profiling
#CXXFLAGS = -pg -g

# for profiling with shark (on the mac)
#CXXFLAGS = -DNDEBUG -g

# := does immediate expansion

#CXXFLAGS := $(CXXFLAGS) -DNDEBUG

CXXFLAGS := $(CXXFLAGS) -Ilib -I../lib

