#!/bin/bash
#deletes all test cases-- fastpc, glpk, v2007
#deletes everything from output folder

delPrefix=""

if [ $# -lt 1 ] #no argument specified
then
   echo -n 'No file prefix specified. Delete all? (y or n): '
   read deleteAll
   if [ "$deleteAll" = "y" ]
   then 
      delPrefix=""
   else
      echo 'Clean cancelled.'
      exit 0
   fi
else
  delPrefix="$1"
fi
    
if [ -d test_cases ] 
then
   rm -f ./test_cases/"$delPrefix"*
fi

if [ -d test_cases_glpk ] 
then
   rm -f ./test_cases_glpk/"$delPrefix"*
fi

if [ -d output ] 
then
   rm -f ./output/"$delPrefix"*
fi

if [ -d profile ]
then
   rm -f ./profile/"$delPrefix"*
fi
